export const ADD_MULTIPLE_BAN_WORK_LOG_REQUEST = 'banWorkLog/ADD_MULTIPLE_BAN_WORK_LOG_REQUEST';
export const ADD_MULTIPLE_BAN_WORK_LOG_SUCCESS = 'banWorkLog/ADD_MULTIPLE_BAN_WORK_LOG_SUCCESS';
export const ADD_MULTIPLE_BAN_WORK_LOG_FAILURE = 'banWorkLog/ADD_MULTIPLE_BAN_WORK_LOG_FAILURE';

export const DELETE_BAN_WORK_LOG_REQUEST = 'banWorkLog/DELETE_BAN_WORK_LOG_REQUEST';
export const DELETE_BAN_WORK_LOG_SUCCESS = 'banWorkLog/DELETE_BAN_WORK_LOG_SUCCESS';
export const DELETE_BAN_WORK_LOG_FAILURE = 'banWorkLog/DELETE_BAN_WORK_LOG_FAILURE';

export const FETCH_BAN_WORK_LOG_REQUEST = 'banWorkLog/FETCH_BAN_WORK_LOG_REQUEST';
export const FETCH_BAN_WORK_LOG_SUCCESS = 'banWorkLog/FETCH_BAN_WORK_LOG_SUCCESS';
export const FETCH_BAN_WORK_LOG_FAILURE = 'banWorkLog/FETCH_BAN_WORK_LOG_FAILURE';
