export const FETCH_VACATION_LIST_REQUEST = 'vacation/FETCH_VACATION_LIST_REQUEST';
export const FETCH_VACATION_LIST_SUCCESS = 'vacation/FETCH_VACATION_LIST_SUCCESS';
export const FETCH_VACATION_LIST_FAILURE = 'vacation/FETCH_VACATION_LIST_FAILURE';
