export const FETCH_CHANGES_AND_ABSENCE_REGISTRATIONS_REQUEST = 'hr/FETCH_CHANGES_AND_ABSENCE_REGISTRATIONS_REQUEST';
export const FETCH_CHANGES_AND_ABSENCE_REGISTRATIONS_SUCCESS = 'hr/FETCH_CHANGES_AND_ABSENCE_REGISTRATIONS_SUCCESS';
export const FETCH_CHANGES_AND_ABSENCE_REGISTRATIONS_FAILURE = 'hr/FETCH_CHANGES_AND_ABSENCE_REGISTRATIONS_FAILURE';

export const FETCH_YEAR_OVERVIEW_REQUEST = 'hr/FETCH_YEAR_OVERVIEW_REQUEST';
export const FETCH_YEAR_OVERVIEW_SUCCESS = 'hr/FETCH_YEAR_OVERVIEW_SUCCESS';
export const FETCH_YEAR_OVERVIEW_FAILURE = 'hr/FETCH_YEAR_OVERVIEW_FAILURE';
