export const FETCH_CONFIG_REQUEST = 'config/FETCH_CONFIG_REQUEST';
export const FETCH_CONFIG_SUCCESS = 'config/FETCH_CONFIG_SUCCESS';
export const FETCH_CONFIG_FAILURE = 'config/FETCH_CONFIG_FAILURE';

export const SAVE_CONFIG_REQUEST = 'config/SAVE_CONFIG_REQUEST';
export const SAVE_CONFIG_SUCCESS = 'config/SAVE_CONFIG_SUCCESS';
export const SAVE_CONFIG_FAILURE = 'config/SAVE_CONFIG_FAILURE';
