export const ADD_SICK_DAY_WORK_LOG_REQUEST = 'sickDayWorkLog/ADD_SICK_DAY_WORK_LOG_REQUEST';
export const ADD_SICK_DAY_WORK_LOG_SUCCESS = 'sickDayWorkLog/ADD_SICK_DAY_WORK_LOG_SUCCESS';
export const ADD_SICK_DAY_WORK_LOG_FAILURE = 'sickDayWorkLog/ADD_SICK_DAY_WORK_LOG_FAILURE';

export const DELETE_SICK_DAY_WORK_LOG_REQUEST = 'sickDayWorkLog/DELETE_SICK_DAY_WORK_LOG_REQUEST';
export const DELETE_SICK_DAY_WORK_LOG_SUCCESS = 'sickDayWorkLog/DELETE_SICK_DAY_WORK_LOG_SUCCESS';
export const DELETE_SICK_DAY_WORK_LOG_FAILURE = 'sickDayWorkLog/DELETE_SICK_DAY_WORK_LOG_FAILURE';

export const FETCH_SICK_DAY_WORK_LOG_REQUEST = 'sickDayWorkLog/FETCH_SICK_DAY_WORK_LOG_REQUEST';
export const FETCH_SICK_DAY_WORK_LOG_SUCCESS = 'sickDayWorkLog/FETCH_SICK_DAY_WORK_LOG_SUCCESS';
export const FETCH_SICK_DAY_WORK_LOG_FAILURE = 'sickDayWorkLog/FETCH_SICK_DAY_WORK_LOG_FAILURE';
