export const ADD_TIME_OFF_WORK_LOG_REQUEST = 'timeOffWorkLog/ADD_TIME_OFF_WORK_LOG_REQUEST';
export const ADD_TIME_OFF_WORK_LOG_SUCCESS = 'timeOffWorkLog/ADD_TIME_OFF_WORK_LOG_SUCCESS';
export const ADD_TIME_OFF_WORK_LOG_FAILURE = 'timeOffWorkLog/ADD_TIME_OFF_WORK_LOG_FAILURE';

export const DELETE_TIME_OFF_WORK_LOG_REQUEST = 'timeOffWorkLog/DELETE_TIME_OFF_WORK_LOG_REQUEST';
export const DELETE_TIME_OFF_WORK_LOG_SUCCESS = 'timeOffWorkLog/DELETE_TIME_OFF_WORK_LOG_SUCCESS';
export const DELETE_TIME_OFF_WORK_LOG_FAILURE = 'timeOffWorkLog/DELETE_TIME_OFF_WORK_LOG_FAILURE';
