export const FETCH_WORK_HOURS_LIST_REQUEST = 'workHours/FETCH_WORK_HOURS_LIST_REQUEST';
export const FETCH_WORK_HOURS_LIST_SUCCESS = 'workHours/FETCH_WORK_HOURS_LIST_SUCCESS';
export const FETCH_WORK_HOURS_LIST_FAILURE = 'workHours/FETCH_WORK_HOURS_LIST_FAILURE';
