export const ADD_USER_REQUEST = 'user/ADD_USER_REQUEST';
export const ADD_USER_SUCCESS = 'user/ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'user/ADD_USER_FAILURE';

export const ARCHIVE_USER_REQUEST = 'user/ARCHIVE_USER_REQUEST';
export const ARCHIVE_USER_SUCCESS = 'user/ARCHIVE_USER_SUCCESS';
export const ARCHIVE_USER_FAILURE = 'user/ARCHIVE_USER_FAILURE';

export const DELETE_USER_REQUEST = 'user/DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'user/DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'user/DELETE_USER_FAILURE';

export const EDIT_USER_REQUEST = 'user/EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = 'user/EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'user/EDIT_USER_FAILURE';

export const FETCH_SUPERVISED_USER_LIST_REQUEST = 'user/FETCH_SUPERVISED_USER_LIST_REQUEST';
export const FETCH_SUPERVISED_USER_LIST_SUCCESS = 'user/FETCH_SUPERVISED_USER_LIST_SUCCESS';
export const FETCH_SUPERVISED_USER_LIST_FAILURE = 'user/FETCH_SUPERVISED_USER_LIST_FAILURE';

export const FETCH_USER_REQUEST = 'user/FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'user/FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'user/FETCH_USER_FAILURE';

export const FETCH_USER_LIST_REQUEST = 'user/FETCH_USER_LIST_REQUEST';
export const FETCH_USER_LIST_SUCCESS = 'user/FETCH_USER_LIST_SUCCESS';
export const FETCH_USER_LIST_FAILURE = 'user/FETCH_USER_LIST_FAILURE';

export const FETCH_USER_LIST_PARTIAL_REQUEST = 'user/FETCH_USER_LIST_PARTIAL_REQUEST';
export const FETCH_USER_LIST_PARTIAL_SUCCESS = 'user/FETCH_USER_LIST_PARTIAL_SUCCESS';
export const FETCH_USER_LIST_PARTIAL_FAILURE = 'user/FETCH_USER_LIST_PARTIAL_FAILURE';

export const RENEW_USER_API_TOKEN_REQUEST = 'user/RENEW_USER_API_TOKEN_REQUEST';
export const RENEW_USER_API_TOKEN_SUCCESS = 'user/RENEW_USER_API_TOKEN_SUCCESS';
export const RENEW_USER_API_TOKEN_FAILURE = 'user/RENEW_USER_API_TOKEN_FAILURE';

export const RENEW_USER_ICAL_TOKEN_REQUEST = 'user/RENEW_USER_ICAL_TOKEN_REQUEST';
export const RENEW_USER_ICAL_TOKEN_SUCCESS = 'user/RENEW_USER_ICAL_TOKEN_SUCCESS';
export const RENEW_USER_ICAL_TOKEN_FAILURE = 'user/RENEW_USER_ICAL_TOKEN_FAILURE';

export const RESET_USER_API_TOKEN_REQUEST = 'user/RESET_USER_API_TOKEN_REQUEST';
export const RESET_USER_API_TOKEN_SUCCESS = 'user/RESET_USER_API_TOKEN_SUCCESS';
export const RESET_USER_API_TOKEN_FAILURE = 'user/RESET_USER_API_TOKEN_FAILURE';

export const RESET_USER_ICAL_TOKEN_REQUEST = 'user/RESET_USER_ICAL_TOKEN_REQUEST';
export const RESET_USER_ICAL_TOKEN_SUCCESS = 'user/RESET_USER_ICAL_TOKEN_SUCCESS';
export const RESET_USER_ICAL_TOKEN_FAILURE = 'user/RESET_USER_ICAL_TOKEN_FAILURE';

export const UNARCHIVE_USER_REQUEST = 'user/UNARCHIVE_USER_REQUEST';
export const UNARCHIVE_USER_SUCCESS = 'user/UNARCHIVE_USER_SUCCESS';
export const UNARCHIVE_USER_FAILURE = 'user/UNARCHIVE_USER_FAILURE';
