export const ADD_USER_REQUEST = 'user/ADD_USER_REQUEST';
export const ADD_USER_SUCCESS = 'user/ADD_USER_SUCCESS';
export const ADD_USER_FAILURE = 'user/ADD_USER_FAILURE';

export const DELETE_USER_REQUEST = 'user/DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'user/DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'user/DELETE_USER_FAILURE';

export const EDIT_USER_REQUEST = 'user/EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = 'user/EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'user/EDIT_USER_FAILURE';

export const FETCH_USER_REQUEST = 'user/FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'user/FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'user/FETCH_USER_FAILURE';

export const FETCH_USER_LIST_REQUEST = 'user/FETCH_USER_LIST_REQUEST';
export const FETCH_USER_LIST_SUCCESS = 'user/FETCH_USER_LIST_SUCCESS';
export const FETCH_USER_LIST_FAILURE = 'user/FETCH_USER_LIST_FAILURE';
