export const FETCH_CONTRACT_LIST_REQUEST = 'contract/FETCH_CONTRACT_LIST_REQUEST';
export const FETCH_CONTRACT_LIST_SUCCESS = 'contract/FETCH_CONTRACT_LIST_SUCCESS';
export const FETCH_CONTRACT_LIST_FAILURE = 'contract/FETCH_CONTRACT_LIST_FAILURE';

export const TERMINATE_CONTRACT_REQUEST = 'contract/TERMINATE_CONTRACT_REQUEST';
export const TERMINATE_CONTRACT_SUCCESS = 'contract/TERMINATE_CONTRACT_SUCCESS';
export const TERMINATE_CONTRACT_FAILURE = 'contract/TERMINATE_CONTRACT_FAILURE';
