export const ADD_WORK_LOG_REQUEST = 'workLog/ADD_WORK_LOG_REQUEST';
export const ADD_WORK_LOG_SUCCESS = 'workLog/ADD_WORK_LOG_SUCCESS';
export const ADD_WORK_LOG_FAILURE = 'workLog/ADD_WORK_LOG_FAILURE';

export const FETCH_WORK_LOG_LIST_REQUEST = 'workLog/FETCH_WORK_LOG_LIST_REQUEST';
export const FETCH_WORK_LOG_LIST_SUCCESS = 'workLog/FETCH_WORK_LOG_LIST_SUCCESS';
export const FETCH_WORK_LOG_LIST_FAILURE = 'workLog/FETCH_WORK_LOG_LIST_FAILURE';
