export const ADD_WORK_LOG_REQUEST = 'workLog/ADD_WORK_LOG_REQUEST';
export const ADD_WORK_LOG_SUCCESS = 'workLog/ADD_WORK_LOG_SUCCESS';
export const ADD_WORK_LOG_FAILURE = 'workLog/ADD_WORK_LOG_FAILURE';

export const DELETE_WORK_LOG_REQUEST = 'workLog/DELETE_WORK_LOG_REQUEST';
export const DELETE_WORK_LOG_SUCCESS = 'workLog/DELETE_WORK_LOG_SUCCESS';
export const DELETE_WORK_LOG_FAILURE = 'workLog/DELETE_WORK_LOG_FAILURE';

export const FETCH_WORK_LOG_REQUEST = 'workLog/FETCH_WORK_LOG_REQUEST';
export const FETCH_WORK_LOG_SUCCESS = 'workLog/FETCH_WORK_LOG_SUCCESS';
export const FETCH_WORK_LOG_FAILURE = 'workLog/FETCH_WORK_LOG_FAILURE';
