export const FETCH_WORK_LOG_LIST_REQUEST = 'workLog/FETCH_WORK_LOG_LIST_REQUEST';
export const FETCH_WORK_LOG_LIST_SUCCESS = 'workLog/FETCH_WORK_LOG_LIST_SUCCESS';
export const FETCH_WORK_LOG_LIST_FAILURE = 'workLog/FETCH_WORK_LOG_LIST_FAILURE';
