export const FETCH_RECENT_SPECIAL_APPROVAL_LIST_REQUEST = 'workMonth/FETCH_RECENT_SPECIAL_APPROVAL_LIST_REQUEST';
export const FETCH_RECENT_SPECIAL_APPROVAL_LIST_SUCCESS = 'workMonth/FETCH_RECENT_SPECIAL_APPROVAL_LIST_SUCCESS';
export const FETCH_RECENT_SPECIAL_APPROVAL_LIST_FAILURE = 'workMonth/FETCH_RECENT_SPECIAL_APPROVAL_LIST_FAILURE';

export const FETCH_SPECIAL_APPROVAL_LIST_REQUEST = 'workMonth/FETCH_SPECIAL_APPROVAL_LIST_REQUEST';
export const FETCH_SPECIAL_APPROVAL_LIST_SUCCESS = 'workMonth/FETCH_SPECIAL_APPROVAL_LIST_SUCCESS';
export const FETCH_SPECIAL_APPROVAL_LIST_FAILURE = 'workMonth/FETCH_SPECIAL_APPROVAL_LIST_FAILURE';

export const FETCH_WORK_MONTH_REQUEST = 'workMonth/FETCH_WORK_MONTH_REQUEST';
export const FETCH_WORK_MONTH_SUCCESS = 'workMonth/FETCH_WORK_MONTH_SUCCESS';
export const FETCH_WORK_MONTH_FAILURE = 'workMonth/FETCH_WORK_MONTH_FAILURE';

export const FETCH_WORK_MONTH_LIST_REQUEST = 'workMonth/FETCH_WORK_MONTH_LIST_REQUEST';
export const FETCH_WORK_MONTH_LIST_SUCCESS = 'workMonth/FETCH_WORK_MONTH_LIST_SUCCESS';
export const FETCH_WORK_MONTH_LIST_FAILURE = 'workMonth/FETCH_WORK_MONTH_LIST_FAILURE';

export const MARK_WORK_MONTH_APPROVED_REQUEST = 'workMonth/MARK_WORK_MONTH_APPROVED_REQUEST';
export const MARK_WORK_MONTH_APPROVED_SUCCESS = 'workMonth/MARK_WORK_MONTH_APPROVED_SUCCESS';
export const MARK_WORK_MONTH_APPROVED_FAILURE = 'workMonth/MARK_WORK_MONTH_APPROVED_FAILURE';

export const MARK_WORK_MONTH_WAITING_FOR_APPROVAL_REQUEST = 'workMonth/MARK_WORK_MONTH_WAITING_FOR_APPROVAL_REQUEST';
export const MARK_WORK_MONTH_WAITING_FOR_APPROVAL_SUCCESS = 'workMonth/MARK_WORK_MONTH_WAITING_FOR_APPROVAL_SUCCESS';
export const MARK_WORK_MONTH_WAITING_FOR_APPROVAL_FAILURE = 'workMonth/MARK_WORK_MONTH_WAITING_FOR_APPROVAL_FAILURE';

export const SET_WORK_TIME_CORRECTION_REQUEST = 'workMonth/SET_WORK_TIME_CORRECTION_REQUEST';
export const SET_WORK_TIME_CORRECTION_SUCCESS = 'workMonth/SET_WORK_TIME_CORRECTION_SUCCESS';
export const SET_WORK_TIME_CORRECTION_FAILURE = 'workMonth/SET_WORK_TIME_CORRECTION_FAILURE';
