export const FETCH_WORK_MONTH_REQUEST = 'workMonth/FETCH_WORK_MONTH_REQUEST';
export const FETCH_WORK_MONTH_SUCCESS = 'workMonth/FETCH_WORK_MONTH_SUCCESS';
export const FETCH_WORK_MONTH_FAILURE = 'workMonth/FETCH_WORK_MONTH_FAILURE';

export const FETCH_WORK_MONTH_LIST_REQUEST = 'workMonth/FETCH_WORK_MONTH_LIST_REQUEST';
export const FETCH_WORK_MONTH_LIST_SUCCESS = 'workMonth/FETCH_WORK_MONTH_LIST_SUCCESS';
export const FETCH_WORK_MONTH_LIST_FAILURE = 'workMonth/FETCH_WORK_MONTH_LIST_FAILURE';
