export const STATUS_OPENED = 'OPENED';
export const STATUS_WAITING_FOR_APPROVAL = 'WAITING_FOR_APPROVAL';
export const STATUS_APPROVED = 'APPROVED';
export const STATUS_REJECTED = 'REJECTED';

export const BAN_WORK_LOG = 'BAN_WORK_LOG';
export const BUSINESS_TRIP_WORK_LOG = 'BUSINESS_TRIP_WORK_LOG';
export const HOME_OFFICE_WORK_LOG = 'HOME_OFFICE_WORK_LOG';
export const MATERNITY_PROTECTION_WORK_LOG = 'MATERNITY_PROTECTION_WORK_LOG';
export const OVERTIME_WORK_LOG = 'OVERTIME_WORK_LOG';
export const PARENTAL_LEAVE_WORK_LOG = 'PARENTAL_LEAVE_WORK_LOG';
export const SICK_DAY_WORK_LOG = 'SICK_DAY_WORK_LOG';
export const SICK_DAY_UNPAID_WORK_LOG = 'SICK_DAY_UNPAID_WORK_LOG';
export const SPECIAL_LEAVE_WORK_LOG = 'SPECIAL_LEAVE_WORK_LOG';
export const TIME_OFF_WORK_LOG = 'TIME_OFF_WORK_LOG';
export const TRAINING_WORK_LOG = 'TRAINING_WORK_LOG';
export const VACATION_WORK_LOG = 'VACATION_WORK_LOG';
export const WORK_LOG = 'WORK_LOG';
