export const STATUS_OPENED = 'OPENED';
export const STATUS_WAITING_FOR_APPROVAL = 'WAITING_FOR_APPROVAL';
export const STATUS_APPROVED = 'APPROVED';
export const STATUS_REJECTED = 'REJECTED';

export const BUSINESS_TRIP_WORK_LOG = 'BUSINESS_TRIP_WORK_LOG';
export const HOME_OFFICE_WORK_LOG = 'HOME_OFFICE_WORK_LOG';
export const TIME_OFF_WORK_LOG = 'TIME_OFF_WORK_LOG';
export const VACATION_WORK_LOG = 'VACATION_WORK_LOG';
export const WORK_LOG = 'WORK_LOG';
